name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Swiftlint
      run: swiftlint
    - name: Build
      run: xcodebuild -scheme DoutakuApp
    - name: Run tests
      run: xcodebuild clean test -scheme DoutakuApp
